# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DSD2025/DSD_practice_for_git/advanced_practice2/project_1/project_1.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
# IP: The module: 'xbip_dsp48_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSD2025/DSD_practice_for_git/advanced_practice2/project_1/project_1.gen/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/DSD2025/DSD_practice_for_git/advanced_practice2/project_1/project_1.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
# IP: The module: 'xbip_dsp48_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSD2025/DSD_practice_for_git/advanced_practice2/project_1/project_1.gen/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
