# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DSD2025/advanced_practice_1/CONV_1D/CONV_1D.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
# IP: The module: 'dsp_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSD2025/advanced_practice_1/CONV_1D/CONV_1D.gen/sources_1/ip/dsp_macro_0/dsp_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/DSD2025/advanced_practice_1/CONV_1D/CONV_1D.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
# IP: The module: 'dsp_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSD2025/advanced_practice_1/CONV_1D/CONV_1D.gen/sources_1/ip/dsp_macro_0/dsp_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
